name: flutter_dmcb_logger
description: A new flutter logger
version: 0.0.2
homepage: https://github.com/zenganiu/flutter_dmcb_logger

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

